alias au="sudo apt-get update"
alias aug="sudo apt-get upgrade"
alias aud="sudo apt-get dist-upgrade"
alias ainstall="sudo apt-get install"
alias apurge="sudo apt-get purge"
alias asearch="apt-cache search"
alias ashow="apt-cache show"
alias ebhose="ssh ebhose@matie.nl"
